'use strict';
// Page markup stays independent of balances, engines and iframe routing.
function renderLobby({session, filter}){
 const games=catalog.filter(g=>g.available&&(filter==='全部'||g.category===filter));
 const upcoming=catalog.filter(g=>!g.available&&(filter==='全部'||g.category===filter));
 return `<div class="welcome"><h1>今天，玩点什么？</h1><span class="lobby-count">${catalog.filter(g=>g.available).length} 款可玩</span></div>
 ${session.visited?`<div class="continue"><div><h2>${gameName(session.activeGame)}</h2><p class="muted">最近玩过</p></div><button class="primary" data-play="${session.activeGame}">回到游戏</button></div>`:''}
 <div class="section-row"><h2 class="sr-only">探索游戏</h2><div class="filters" aria-label="游戏分类">${['全部','益智','反应','概率'].map(c=>`<button class="filter" data-filter="${c}" aria-pressed="${filter===c}">${c}</button>`).join('')}</div></div>
 <div class="catalog">${games.map(g=>`<button class="game-card" data-play="${g.id}" aria-label="${g.name}，${g.cost}，进入游戏"><div class="cover ${g.cover}"><span class="card-category">${g.category}</span><span class="icon-motion" aria-hidden="true"><i class="icon-spark"></i><span class="lobby-art art-${g.id}"></span><i class="icon-spark"></i></span></div><div class="game-details"><h2>${g.name}</h2><p class="game-description">${g.description}</p><div class="card-bottom"><span class="entry-cost">${g.cost}</span><span class="play-label">进入游戏 <span aria-hidden="true">›</span></span></div></div></button>`).join('')}</div>
 ${upcoming.length?`<section class="upcoming" aria-label="即将上线"><h2>即将上线</h2><div class="upcoming-list">${upcoming.map(g=>`<span>${g.name}</span>`).join('')}</div></section>`:''}
 <p class="catalog-footer">模拟积分仅供体验，刷新后重置。</p>`;
}

function renderPlatformPage({page, session, filter}){if(page==='games'){return renderLobby({session, filter})}else if(page==='rewards'){return `<h1>我的奖励</h1><p class="muted">游戏积分与链上资产，分别查看。</p><div class="panel-grid"><section class="panel"><h2>本次体验积分</h2><div class="balance">${formatPoints(session.points)}<span>积分</span></div><p class="muted">首次赠送 1,000 积分；各游戏每局消耗 50 积分，奖励含本局投入。</p></section><section class="panel"><h2>链上资产</h2><div class="empty">尚未接入钱包</div><p class="muted">当前版本没有充值、提现或真实交易。</p></section></div><section class="panel list-panel"><h2>积分明细</h2>${session.ledger.slice().reverse().map(r=>`<div class="record"><div>${r.label}<small>${r.time}</small></div><span class="${r.amount>0?'positive':'muted'}">${r.amount>0?'+':''}${formatPoints(r.amount)} 积分</span></div>`).join('')}</section><p class="notice">积分仅用于本次 Demo 体验，刷新后重置为初始赠送积分，不具有货币价值。</p>`}else{return `<h1>我的</h1><div class="profile"><span class="avatar">P</span><div><h2>游客玩家</h2><p class="muted">先玩一局，轻松探索</p></div></div><div class="panel-grid"><section class="panel"><h2>本次游戏记录</h2>${session.rounds.length?session.rounds.slice().reverse().map(r=>`<div class="record"><div>${gameName(r.gameId)}<small>${r.time} · ${r.seconds} 秒</small></div><span class="${r.won?'positive':'muted'}">${r.gameId==='horse'?('第 '+r.rank+' 名 · '+r.amount+' 积分'):r.gameId==='plinko'?('落袋 '+r.multiplier+'× · '+r.amount+' 积分'):r.gameId==='dice'?(r.won?'命中 · '+r.amount+' 积分':'未命中 · 0 积分'):r.gameId==='rocket'?(r.won?'已收取 '+r.amount+' 积分':'已坠毁 · 0 积分'):(r.won?'已收取 '+formatPoints(r.amount)+' 积分':r.state==='forfeited'?'已结束 · 0 积分':'踩到地雷 · 0 积分')}</span></div>`).join(''):'<div class="empty">还没有完成的游戏。</div><button class="primary" data-play>开始第一局</button>'}</section><section><div class="rows"><button class="row-button" data-help="account"><span>账户与钱包</span><span>未接入 ›</span></button><button class="row-button" data-help="rules"><span>玩法说明</span><span>游戏规则 ›</span></button><button class="row-button" data-help="about"><span>关于 PLAYROOM</span><span>Demo ›</span></button></div><p class="notice">游戏记录仅保留在本次页面会话中。</p></section></div>`}}
function formatPoints(n){return n.toLocaleString('zh-CN',{maximumFractionDigits:2})}
function help(kind){const copy={account:['账户与钱包','当前使用游客模式，无需注册即可试玩。\n账户绑定和钱包连接尚未接入。'],rules:['游戏怎么玩？','金币扫雷：54 格中固定藏着 10 颗雷，每局开始时随机生成。\n每次只翻开一格，没有数字提示或首次保护。金币颜色不提供线索。\n每局消耗 50 积分，成功揭开至少一格后可随时收取。奖励含本局投入；踩雷时本局奖励归零，开局消耗不退还。\n奖励按理论返还率 97% 计算，保留两位小数并向下取整，实际返还率略低。揭开全部安全格自动收取，返回大厅可保留当前局。\n\n小火箭：每局消耗 50 积分。飞行越久倍率越高，可随时主动收取；坠毁前未收取则本局奖励归零。收取得分含本局投入，切出页面不会暂停。\n理论返还率 97%，每局理论平均净收益约 −1.5 积分。没有起飞保护，约 3% 开局即坠毁；喷焰与音效不预示坠毁。倍率向下保留两位小数，到达 10× 自动收取 500 积分。\n\n三骰挑战：每局消耗 50 积分。可选大小、指定总点数、任意三同号；大小排除三同号。命中后自动发放界面所示奖励（含投入），未命中无奖励。\n\n闪电跑道：每局 50 积分，选择入口释放弹珠，按落袋倍率自动发放积分（含投入）；低于 1 倍会损失部分投入。返回大厅不暂停结算。\n\n星际赛马：每局 50 模拟积分，四匹马选一匹。每匹马任一名次的概率均为 25%，第 1–4 名到账 140、40、14、0 积分（含投入），理论返还率 97%。开赛时随机决定名次，再播放竞速动画。返回大厅后继续自动结算。'],about:['关于 PLAYROOM','一个轻量休闲游戏平台 Demo。\n当前可玩：金币扫雷、小火箭、三骰挑战、闪电跑道、星际赛马。其他游戏正在筹备中。\n所有奖励均为模拟积分，不涉及真实资产。']};document.getElementById('help-title').textContent=copy[kind][0];document.getElementById('help-text').textContent=copy[kind][1];document.getElementById('help').showModal()}
